# Borrows references from https://github.com/marketplace/actions/install-with-cpanm
name: integration-test

# Run this action whenever one pushes to repository or creates a pull request
on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    name: "perl v${{ matrix.perl-version }}"

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.30"

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    services:
      faktory:
        image: contribsys/faktory:latest
        ports:
          - 7419:7419
          - 7420:7420

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install perl dependencies via cpan
        uses: perl-actions/install-with-cpanm@v1.1
        with:
          cpanfile: "cpanfile"
          sudo: false

      - name: Setup docker compose and run Faktory
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          docker-compose -v
          docker-compose -f docker-compose.yml up

      - name: Test to see if faktory server is running
        run: "curl --verbose --silent --output /dev/null http://localhost:${{ job.services.faktory.ports['7420'] }}"

      - name: Run tests for library
        run: make tests

